name: vitalkeep
description: "A new Flutter project."

publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Añadí el rango de versiones, por si quieres más seguridad

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  flutter_blue_plus: ^1.34.5  # Solo mantener este paquete
  flutter_background_service: ^5.0.10
  http: 1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
